variables:
  SHOTGUN_TEST_VERSION:
    value: "$CI_COMMIT_SHA"
    description: "version to be tested"

stages:
  - performance
  - performance2

### Job Definitions

# Jobs in the precheck stage

resolver-shotgun-pipeline-generator:
  stage: performance
  tags:
    - linux-benchmarking
  dependencies: []
  variables:
    GIT_STRATEGY: "none"
    PARENT_PIPELINE_ID: "$CI_PIPELINE_ID"
  image: "$CI_REGISTRY/isc-projects/images/shotgun-controller"
  script:
    - echo "version under test $SHOTGUN_TEST_VERSION"
    - test -d bind-qa && git fetch -C bind-qa || git clone --single-branch --branch=shotgun --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.isc.org/isc-private/bind-qa.git
    - git -C bind-qa clean -ffxdq
    - git -C bind-qa reset --hard origin/shotgun
    - bind-qa/shotgun/shotgunrunner.py > child-pipeline.yaml
  artifacts:
    paths:
      - child-pipeline.yaml
      - combinations.json
    expire_in: "1 hour"
  timeout: 5m

resolver-shotgun-child-pipeline:
  stage: performance2
  trigger:
    include:
      - artifact: child-pipeline.yaml
        job: resolver-shotgun-pipeline-generator
    strategy: depend
