variables:
  SHOTGUN_TEST_VERSION:
    value: "$CI_COMMIT_SHA"
    description: "version(s) to be tested (commit or branch or tag name)"
  SHOTGUN_SCENARIO:
    value: "udp"
    description: "protocol combination(s) to be tested, must be one of https://gitlab.nic.cz/knot/resolver-benchmarking/-/tree/master/roles/shotgun/files"
  SHOTGUN_TRAFFIC_MULTIPLIER:
    value: 10
    description: "client traffic volume multiplier(s); base value 1 = roughly 8 k QPS; start with multiplier 10; max. 40"
  SHOTGUN_ROUNDS:
    value: 3
    description: "repeat test for each combination of (version, scenario, traffic multiplier) this many times; test against reference v9_11_31 is always run once; three runs recommended to detect noise"
  SHOTGUN_DURATION:
    value: 60
    description: "test length in seconds, max 900 s"
  EXAMPLE_SHOTGUN_TEST_VERSION_WITH_MULTIPLE_VALUES:
    value: "['main', 'v9_16_15']"
    description: "an example how to specify multiple values for version; works the same way for (scenario, traffic multiplier)"

stages:
  - performance
  - performance2

### Job Definitions

# Jobs in the precheck stage

resolver-shotgun-pipeline-generator:
  stage: performance
  tags:
    - linux-benchmarking
  dependencies: []
  variables:
    GIT_STRATEGY: "none"
  image: "$CI_REGISTRY/isc-projects/images/shotgun-controller"
  script:
    - echo "version under test $SHOTGUN_TEST_VERSION"
    - test -d bind-qa && git fetch -C bind-qa || git clone --single-branch --branch=shotgun-experiment-resolvers --depth=1 https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.isc.org/isc-private/bind-qa.git
    - git -C bind-qa clean -ffxdq
    - git -C bind-qa reset --hard origin/shotgun-experiment-resolvers
    - bind-qa/shotgun/shotgunrunner.py > child-pipeline.yaml
  artifacts:
    paths:
      - child-pipeline.yaml
      - combinations.json
    expire_in: "1 week"
  timeout: 5m

resolver-shotgun-child-pipeline:
  stage: performance2
  variables:
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include:
      - artifact: child-pipeline.yaml
        job: resolver-shotgun-pipeline-generator
    strategy: depend
