#!/bin/sh

# SPDX-FileCopyrightText: Internet Systems Consortium, Inc. ("ISC")
#
# SPDX-License-Identifier: MPL-2.0

status=0
find */*/win32 win32utils -name \*.in |
sed -e '/\/Makefile.in$/d' \
    -e 's/.in$/"/' \
    -e 's/^/"..\//' \
    -e 's/"..\/win32utils\//"/' |
while read f
do
	if grep -F "$f" win32utils/Configure > /dev/null
	then
		:
	else
		echo "missing $f from win32utils/Configure"
		status=1
	fi
done
if test -f win32utils/Configure
then
	cd win32utils
	perl Configure checkfiles 2> /dev/null || status=1
fi
exit $status
